name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Dependency
        run: |
          sudo apt update
          sudo apt install emacs-nox rsync

      - name: Checkout template
        uses: actions/checkout@master
        with:
          repository: Flurando/gh-org
          token: ${{ secrets.GITHUB_TOKEN }}
          path: repo

      - name: Remove example content folder
        working-directory: repo
        run: |
          rm -rf content/

      - name: Checkout
        uses: actions/checkout@master
        with:
          path: repo/content

      - name: Substitute config file if provided
        working-directory: repo
        run: |
          if [ -f content/config.el ]; then
            echo config file found!
            mv -f ./content/config.el ./config.el
          else
            echo config file is absent, using default!
          fi

      - name: Change config.el load path to absolute
        working-directory: repo
        run: |
          sed -i "s|config.el|$(pwd)/config.el|g;" ./build-site.el

      - name: Build pages from org files
        working-directory: repo
        run: |
          make

      - name: sync all static files as is to output folder
        working-directory: repo
        run: |
          rsync -chavzP --exclude="*~" --exclude="*#" --exclude=".*" --exclude="*.org" --exclude="config.el" content/* public/

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/org-focus/org-focus/repo/public
