name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Dependency
        run: |
          sudo apt update
          sudo apt install emacs

      - name: Checkout template
        uses: actions/checkout@master
        with:
          repository: Flurando/gh-org
          token: ${{ secrets.GITHUB_TOKEN }}
          path: repo

      - name: Remove example content folder
        working-directory: repo
        run: |
          rm -rf content/

      - name: Checkout
        uses: actions/checkout@master
        with:
          path: repo/content

      - name: Substitute config file if provided
        working-directory: repo
        run: |
          if [ -f content/config.el ]; then
            echo config file found!
            mv -f ./content/config.el ./config.el
          else
            echo config file is absent, using default!
          fi

      - name: Build
        working-directory: repo
        run: |
          if [ -d content/static ]; then
            mv content/static ./
            make
            mkdir -p public
            mv static/* public/
          else
            make
          fi

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
